name = "chessforge-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "MATCHES"
class_name = "MatchDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MatchDurableObject"]
